spring:
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2     # (1) Context path
  datasource:
    url: jdbc:h2:mem:code-review    # (2) JDBC URL
  redis:
    host: localhost
    port: 6379
    pool:
      max-idle: 10
      min-idle: 0
