version: '3.7'
services:
  es:
    build:
      context: .
      args:
        ELK_VERSION: 8.5.1
    container_name: es
    environment:
      - node.name=single-node
      - cluster.name=code
      - discovery.type=single-node
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - es-bridge

  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:8.5.1
    environment:
      SERVER_NAME: kibana
      ELASTICSEARCH_HOSTS: http://es:9200
    ports:
      - "5601:5601"
    depends_on:
      - es
    networks:
      - es-bridge

networks:
  es-bridge:
    driver: bridge